### ISSUE TITLE
Great Job!

### ISSUE THREAD

**Issue by resslr** [rifsxd/blazefetch#1]
Not an issue, but a note of appreciation. This is great man!

Great job on this project! This is amazing!

One suggestion that would be unique:
Time or Network Status (Connected, Disconnected, Wired/Ethernet)

Amazing job on this :+1:

**Comment by rifsxd** [comment]
nice idea i will look into it

**Comment by rifsxd** [comment]
![image](https://github.com/rifsxd/blazefetch/assets/33044977/c340f21b-5678-42e1-87e0-ddbc53a60f5c)

added network to test code

**Comment by resslr** [comment]
> ![image](https://github.com/rifsxd/blazefetch/assets/33044977/c340f21b-5678-42e1-87e0-ddbc53a60f5c)
> 
> 
> 
> added network to test code

Sick!
