### ISSUE TITLE
[Feat Request] Be able to set ALL parameters with ENV variables.

### ISSUE THREAD

**Issue by xplshn** [rifsxd/blazefetch#4]
That's it, for example, let's say I wanted to change the OS name, I'd set `BLF_OS="Andes"`, instead of `Alpine` for example, same would go for the ascii art, and it'd be great if we could directly set an ascii art copy pasta like:
```
BLF_cASCII="
   /\ /\
  // \  \
 //   \  \
///    \  \
//      \  \
         \
"
```

**Comment by rifsxd** [comment]
might look into this, thanks for the suggestion.

**Comment by rifsxd** [comment]
![image](https://github.com/rifsxd/blazefetch/assets/33044977/f84d013f-6c1d-4c1e-950b-83922adb519d)

something like this?

**Comment by rifsxd** [comment]
ignore the stupid errors lol im on WSL

**Comment by rifsxd** [comment]
![image](https://github.com/rifsxd/blazefetch/assets/33044977/d012b27e-d15d-4573-987f-496d631e5e60)
